export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? process.env.FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? process.env.FORGE_API_KEY ?? "",
  spellLlmProvider: process.env.SPELL_LLM_PROVIDER ?? "groq",
  spellLlmApiKey: process.env.SPELL_LLM_API_KEY ?? "",
  spellLlmFallbackProviders: process.env.SPELL_LLM_FALLBACK_PROVIDERS ?? "gemini,openrouter",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  openrouterApiKey: process.env.OPENROUTER_API_KEY ?? "",
  imageGenApiKey: process.env.IMAGE_GEN_API_KEY ?? "",
};
